# Generated by Django 5.0.3 on 2024-03-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logos',
            name='immagine',
            field=models.FileField(upload_to=''),
        ),
    ]
