# Generated by Django 5.0.3 on 2024-03-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_wallet', '0002_alter_logos_immagine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='logos',
            new_name='Logo',
        ),
    ]
