# Generated by Django 5.0.3 on 2024-03-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_wallet', '0003_rename_logos_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
