# Generated by Django 5.0.3 on 2024-03-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_wallet', '0008_crypto_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crypto',
            old_name='buyPrice',
            new_name='buyValue',
        ),
        migrations.AddField(
            model_name='crypto',
            name='actualValue',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
